//! Integration tests for daemon-desktop modules.

use daemon_desktop::config::DesktopConfig;
use daemon_desktop::hyprland::HyprlandManager;
use daemon_desktop::session::SessionManager;
use daemon_desktop::startup::StartupOrchestrator;
use std::fs;

#[test]
fn test_desktop_config_validation() {
    let mut config = DesktopConfig::default();
    assert!(config.validate().is_ok());

    config.theme = "".to_string();
    assert!(config.validate().is_err());
}

#[test]
fn test_desktop_config_load_save() -> Result<(), Box<dyn std::error::Error>> {
    let temp_dir = std::env::temp_dir();
    let temp_file = temp_dir.join("daemon_desktop_test_config.toml");

    let config = DesktopConfig {
        theme: "test-theme".to_string(),
        wallpaper: "test-wallpaper.png".to_string(),
        cursor_theme: "test-cursor".to_string(),
        font_name: "test-font".to_string(),
        ..DesktopConfig::default()
    };

    let content = toml::to_string_pretty(&config)?;
    fs::write(&temp_file, content)?;

    let loaded = DesktopConfig::load_from_file(&temp_file)?;
    assert_eq!(loaded.theme, "test-theme");
    assert_eq!(loaded.wallpaper, "test-wallpaper.png");

    let _ = fs::remove_file(&temp_file);
    Ok(())
}

#[test]
fn test_hyprland_config_generator() -> Result<(), String> {
    let config = DesktopConfig::default();
    let config_str = HyprlandManager::generate_config(&config)?;
    assert!(config_str.contains("Hyprland Config Generated by DaemonOS"));
    assert!(config_str.contains("exec-once = daemon-panel && daemon-launcher"));
    Ok(())
}

#[test]
fn test_session_manager_lifecycle() -> Result<(), String> {
    let config = DesktopConfig::default();
    let mut session = SessionManager::new();
    assert!(!session.is_active());

    session.start_session(&config)?;
    assert!(session.is_active());
    Ok(())
}

#[test]
fn test_startup_orchestrator() {
    let config = DesktopConfig::default();
    let cmds = StartupOrchestrator::build_commands(&config);
    assert_eq!(cmds.len(), 2);
    assert_eq!(cmds[0], "daemon-panel");
}
