//! Hyprland integrations and configuration generation.

use crate::config::DesktopConfig;
use which::which;

/// Manages detecting and configuring the Hyprland compositor.
pub struct HyprlandManager;

impl HyprlandManager {
    /// Detect if the Hyprland window manager executable is present on the system.
    pub fn detect_installation() -> bool {
        which("hyprland").is_ok()
    }

    /// Generate a Hyprland configuration string from configuration templates.
    ///
    /// # Errors
    ///
    /// Returns an error string if configuration validation checks fail.
    pub fn generate_config(config: &DesktopConfig) -> Result<String, String> {
        config.validate()?;
        let template = r#"
# Hyprland Config Generated by DaemonOS
monitor=,preferred,auto,1

exec-once = [STARTUP_COMMANDS]

input {
    kb_layout = us
    follow_mouse = 1
}

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}
"#;
        let startup_str = config.startup_commands.join(" && ");
        let rendered = template.replace("[STARTUP_COMMANDS]", &startup_str);
        Ok(rendered)
    }
}
