name: Formatting Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Stable Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Formatting Check
        run: cargo fmt --check
